version: '2'
services:
    load_balancer:
        image: haproxy:latest
        container_name: x-load_balancer
        ports:
            - "80:80"
            - "443:443"
            - "1936:1936"
        volumes:
            - ./load_balancer:/usr/local/etc/haproxy/

    app_server:
        image: app_server:latest
        container_name: x-app_server
        depends_on:
            - passenger
        ports:
            - "3000:3000"

    passenger:
        image: passenger:5.0.28
        container_name: x-passenger
        build:
            context: ./passenger/
            dockerfile: Dockerfile
            args:
                PASSENGER_VERSION: "5.0.28"



